name: polo_3.6
channels:
  - defaults
dependencies:
  - _tflow_select=2.2.0=eigen
  - astor=0.8.1=py36haa95532_0
  - blas=1.0=mkl
  - ca-certificates=2021.1.19=haa95532_0
  - coverage=5.4=py36h2bbff1b_2
  - cython=0.29.21=py36hd77b12b_0
  - h5py=2.10.0=py36h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2020.2=254
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - libprotobuf=3.14.0=h23ce68f_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36h196d8e1_0
  - mkl_fft=1.2.1=py36h46781fe_0
  - mkl_random=1.1.1=py36h47e9c7a_0
  - openssl=1.1.1j=h2bbff1b_0
  - pip=21.0.1=py36haa95532_0
  - pyreadline=2.1=py36_1
  - python=3.6.12=h5500b2f_2
  - scipy=1.5.2=py36h9439919_0
  - setuptools=52.0.0=py36haa95532_0
  - six=1.15.0=py36haa95532_0
  - sqlite=3.33.0=h2a8f88b_0
  - tensorboard=1.14.0=py36he3c9ec2_0
  - tensorflow=1.14.0=eigen_py36hf4fd08c_0
  - tensorflow-base=1.14.0=eigen_py36hdbc3f0e_0
  - tensorflow-estimator=1.14.0=py_0
  - termcolor=1.1.0=py36haa95532_1
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py36h7fe50ca_0
  - wrapt=1.12.1=py36he774522_1
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - absl-py==0.9.0
    - altgraph==0.17
    - certifi==2018.8.24
    - chardet==3.0.4
    - cycler==0.10.0
    - future==0.18.2
    - gast==0.3.3
    - google-pasta==0.2.0
    - grpcio==1.30.0
    - idna==2.10
    - importlib-metadata==1.7.0
    - jinja2==2.11.2
    - kiwisolver==1.1.0
    - lxml==4.5.2
    - macholib==1.14
    - markdown==3.2.2
    - markupsafe==1.1.1
    - matplotlib==3.0.3
    - molmass==2019.1.1
    - numpy==1.18.5
    - pefile==2019.4.18
    - pillow==7.2.0
    - protobuf==3.12.2
    - pyinstaller==3.6
    - pyparsing==2.4.7
    - pyqt5==5.15.0
    - pyqt5-sip==12.8.0
    - python-dateutil==2.8.1
    - python-pptx==0.6.18
    - pywin32-ctypes==0.2.0
    - requests==2.24.0
    - urllib3==1.25.10
    - xlsxwriter==1.2.9
    - zipp==1.2.0
prefix: C:\Users\eholleman\Anaconda3\envs\polo_3.6
